---

- name: Check OS Requirements
  include_tasks: "{{ ansible_os_family }}/check_os_requirements.yml"

- name: Uninstall old versions of Docker
  package:
    name: "{{ docker_old_packages }}"
    state: absent
  when: docker_uninstall_old_versions
