---

- name: Determine Linux distribution
  debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_distribution_release }})"

- name: Gather {{ ansible_os_family }} OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check prerequisites
  include_tasks: check_prerequisites.yml

- name: Install Docker Engine
  include_tasks: install_docker_amazon.yml if {{ ansible_os_family }} == "amazon" else install_docker_engine.yml
  
  - name: Check certs exist
   stat: path=/etc/letsencrypt/live/{{ rootDomain }}/fullchain.pem
   register: st

- include: "{{ './_common/check-certs-renewable.yaml' if st.stat.exists else './_common/create-certs.yaml' }}"

# Post installation steps for Linux

- name: Manage Docker as a non-root user
  include_tasks: manage_as_non_roor_user.yml
  when: docker_users is defined

- name: Configure Docker to start on boot
  include_tasks: configure_to_start_on_boot.yml
  when: docker_start_on_boot

- name: Ensure handlers are notified to avoid firewall conflicts
  meta: flush_handlers

- name: Install Docker SDK for Python
  include_tasks: install_sdk_for_python.yml
  when: docker_pip_packages is defined
