---

- name: Install the latest version of Docker
  apt:
    name: "{{ docker_pkg_name }}"
    state: latest
    update_cache: yes

- name: Start the Docker daemon
  service:
    name: docker
    state: started

- name: Verify that docker is installed correctly by running the {{ docker_test_container_name }} image
  docker_container:
    name: "{{ docker_test_container_name }}"
    image: "{{ docker_test_container_image }}"
    state: started

- name: Stop and remove the {{ docker_test_container_name }} image
  docker_container:
    name: "{{ docker_test_container_name }}"
    state: absent