---

# Manager Docker as a non-root user

- name: Create the docker group
  group:
    name: docker
    state: present
  when: docker_group_members is defined

- name: Add users to the docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_group_members }}"
  when: docker_group_members is defined

# Adjust memory and swap accounting

# TODO

# Enable UFW forwarding

- name: Verify that UFW is enabled
  shell: ufw status
  register: ufw_status_output
  when: docker_ufw_enable_forwarding
  changed_when: false

- name: Set the DEFAULT_FORWARD_POLICY to ACCEPT
  ufw:
    policy: "{{ docker_ufw_default_forward_policy }}"
  when: (ufw_status_output is defined) and (ufw_status_output.stdout|regex_replace( '^Status:\s(.*)$', '\\1' ) == 'active')

- name: Configure UFW to allow incoming connections on the Docker port
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.to_port }}"
    proto: "{{ item.protocol }}"
  with_items: "{{ docker_ufw_rules }}"
  notify: Reload UFW
  when: (ufw_status_output is defined) and (ufw_status_output.stdout|regex_replace( '^Status:\s(.*)$', '\\1' ) == 'active') and (docker_ufw_rules is defined)

# Configure a DNS server for use by Docker

# TODO

# Configure Docker to start on boot

- name: Configure Docker to start on boot
  systemd:
    name: docker
    state: started
  when: (docker_start_on_boot) and (ansible_distribution_version|version_compare(15.04, '>='))